### PR TITLE
Getfilefix

### PR DESCRIPTION
**Pull request by mattleblanc**

### CODE REVIEW

**Comment by kratsg** [comment]
This one won't be merged. RootPy has `get_file` since it breaks up all camel-casing names into the lowercase variants. Is there a reason why one works and the other doesn't?

```
>>> from rootpy.io import File
>>> File.get_file
<ROOT.MethodProxy object at 0x109cb5490>
>>> File.GetFile
<ROOT.MethodProxy object at 0x109cc0510>
```

**Comment by mattleblanc** [comment]
`get_file` didn't work for me at all -- I had to change it in order to get things running.

```
An exception was caught!
Traceback (most recent call last):
  File "totw.py", line 267, in <module>
    did = get_did(hist)
  File "totw.py", line 151, in get_did
    m = did_regex.search(hist.get_directory().get_file().name)
AttributeError: 'TDirectoryFile' object has no attribute 'get_file'
```

**Comment by kratsg** [comment]
`AttributeError: 'TDirectoryFile' object has no attribute 'get_file'` -- it seems weird to me that you've got a TDirectoryFile there.

**Comment by kratsg** [comment]
Was this working without this fix for you after we discussed it? I can merge the changes.

**Pull request closed without merging**
